### ISSUE TITLE
No way to get the mapping at a path position

### ISSUE THREAD

**Issue by adamnovak** [ekg/xg#9]
I can get the ID of the node at a path position with `node_at_path_position`, but there's no way to get the corresponding `Mapping` object, without pulling out the entire `Path` manually.

There should be a `mapping_at_path_position` function.

**Comment by adamnovak** [comment]
Actually, you can't pull out the path manually either, since `xg::XG::path(std::string const&) const` isn't written.

**Comment by ekg** [comment]
I was working on xg paths this evening. But I didn't provide this. The
mapping gets encoded across a number of elements so it needs to be
reconstructed.

**Comment by ekg** [comment]
I think it makes a lot of sense. If you can wait until my update tomorrow
please do as I'm making a number of other edits to XGPath.

Paths in xg are in a difficult spot for another reason. I'm using a
sdsl-lite compressed suffix array to store their names, but this is not
thread safe due to a single cache which the select support uses. I would
love to fix this upstream because it should be possible to store lots of
named paths. I'm thinking annotations like genes, exons, and transcripts.
But the other solution is to hack around it in xg.
